CREATE TABLE users (
    pk BIGSERIAL PRIMARY KEY,
    username VARCHAR(150) UNIQUE NOT NULL CHECK(LENGTH(username) BETWEEN 3 AND 150),
    password VARCHAR(150) NOT NULL,
    about VARCHAR(256) DEFAULT NULL,
    age SMALLINT CHECK(age IS NULL OR age BETWEEN 1 AND 255) DEFAULT NULL,
    disabled BOOLEAN NOT NULL DEFAULT FALSE
);
